Hit position
SND-LHC/advsndsw pull request #15
Opened 2024-08-11 17:58 UTC by siilieva

First AdvTarget tracking in place!

@olantwin, please xcheck the change in the Digi task regarding the local position coordinate used to determine the strip.
With this change I get good comparison MC points-> MC hits comparisons:
![Screenshot from 2024-08-10 18-13-29](https://github.com/user-attachments/assets/cc5bf9eb-5f66-49f5-82f5-5cd0bf7cad54)

ps to all reviewers: Feel free to skip the revision of the bulk changes in the tracker - it works and passes the pre-commit tests.

2024-08-12 12:18 UTC, olantwin requested changes
Some nitpicks, looks good to me otherwise.

2024-08-12 12:18 UTC, olantwin commented on shipLHC/AdvTarget.h
> +    /** mean position of strips associated with readout channel **/
Shouldn't it be then end-points, not the mean? Would be good to also mention whether this is opposite corners, centre line or other.

2024-08-12 12:18 UTC, olantwin commented on python/TrackingParams_AdvSND_Aug2024.xml
> +     <!-- Helpers to select one HT space maxima among many.
maximum

2024-08-12 12:18 UTC, olantwin commented on python/TrackingParams_AdvSND_Aug2024.xml
> +          The n-th quantile of found peaks along 'slope' axis(yH axis above) must enlose
enclose

2024-08-12 12:18 UTC, olantwin commented on python/TrackingParams_AdvSND_Aug2024.xml
> +     <!-- Helpers to select one HT space maxima among many.
maximum

2024-08-12 12:18 UTC, olantwin commented on python/TrackingParams_AdvSND_Aug2024.xml
> +          The n-th quantile of found peaks along 'slope' axis(yH axis) must enlose
enclose

2024-08-13 15:09 UTC, olantwin commented
Could you please make the analogous change for the MuFilter as well? Should be a matter of copy paste.

2024-08-13 15:46 UTC, siilieva commented
> Could you please make the analogous change for the MuFilter as well? Should be a matter of copy paste.

what about testing? Do we know it will provide correct result. I have not tested that system.
ps. I can make a test tomorrow morning.

2024-08-14 08:34 UTC, olantwin commented
I think a simple closure test would be good and also sufficient: are the true coordinates of the MC points contributing within between the end points returned by the geometry?

Probably won't be able to do it today, so if you could manage, that would be amazing.

2024-08-16 17:10 UTC, siilieva commented
pushed the changes mentioned above by @olantwin  as separate commits - will reorder and squash before the final rebase onto the `main`
Fixed the AdvMuFilter strip determination and checked it using NStrips(btw 0-767) and also using the now commited 2dED:
![Screenshot from 2024-08-16 19-05-29](https://github.com/user-attachments/assets/386f85ed-403a-4c9a-9b5f-1ea581ea7f50)


note: the hitColour option for the display needs optimization in terms of timing performance  - can be very slow for busy events.
![Screenshot from 2024-08-16 19-10-02](https://github.com/user-attachments/assets/a52520ee-3795-496d-b5db-dae941fe7234)

2024-08-19 07:39 UTC, olantwin approved these changes
I'd normally complain about one-line if statements and commented code in the event display, but in the interest of time, we can fix those later :)

Thanks a lot for all these fixes and improvements!

Shall I rebase as is, or do you want to squash some commits together to have a nicer history?

2024-08-19 08:45 UTC, siilieva commented
> I'd normally complain about one-line if statements and commented code in the event display, but in the interest of time, we can fix those later :)
> 
> Thanks a lot for all these fixes and improvements!
> 
> Shall I rebase as is, or do you want to squash some commits together to have a nicer history?

I will quickly do some re-ordering and squashing :D

2024-08-19 09:01 UTC, olantwin commented
Ok! Ping me in case another review is needed.

2024-08-19 09:04 UTC, siilieva commented
> Ok! Ping me in case another review is needed.

It is done and I will 'rebase' now. Looks good.

2024-08-19 09:05 UTC, merged